name: CI-Flow

on: 
  push:
    branches:["main"]
  pull_request:
    branches:["main"]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 3. Pull the code from the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 4. Set up the environment (e.g., Node.js)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 5. Run commands
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test


